version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs: 
  jest-tests:
    docker:
      - image: cimg/node:13.11.0
    steps: 
      - checkout
      - restore_cache:
          name: Restore yarn package cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install node modules
          command: yarn install

      - save_cache:
          name: Save yarn package cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          command: yarn test

workflows:
  run-tests:
    jobs:
      - jest-tests
